#LEARNING NUMPY
##Numpy
###Numpy

In [ ]:
import numpy as np #np = numpy

In [ ]:
l1 = [1,2,3]
arr1 = np.array(l1) 
#or arr1 = np.array([1,2,3])
#converted list tuple also

In [ ]:
print(l1)
print(arr1)

[1, 2, 3]
[1 2 3]


## 0-D, 1-D, 2-D and so on

In [ ]:
zeroD = np.array(3)
oneD = np.array([1,2,3])
twoD = np.array([[1,2,3],[2,3,4]])

In [ ]:
print(zeroD)
print(oneD)
print(twoD)

3
[1 2 3]
[[1 2 3]
 [2 3 4]]


###Array indexing

In [ ]:
arr1 = np.array([5,6,7])
print(arr1[2])

7


In [ ]:
l1 = [1,2,3]
print(l1[0])

1


In [ ]:
twoD = np.array([[1,2,3],[2,3,4],[7,8,9]])
print(twoD)

[[1 2 3]
 [2 3 4]
 [7 8 9]]


In [ ]:
print(twoD[0])
print(twoD[1])
print(twoD[1][2])

[1 2 3]
[2 3 4]
4


##slicing

In [ ]:
arr1 = np.array([5,6,7,8,9,10,11,12])
print(arr1)

[ 5  6  7  8  9 10 11 12]


In [ ]:
print(arr1[0:3])
print(arr1[2:6])

[5 6 7]
[ 7  8  9 10]


In [ ]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr)
print(arr[0][2:5])
print(arr[1][2:])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[3 4 5]
[ 8  9 10]


In [ ]:
l1 = ['Hello', 5, 4.333, True, False]
print(type(l1[0]))
l2 = [5,5,4.33,2,2]
print(type(l1[0]))

<class 'str'>
<class 'str'>


In [ ]:
arr2 = np.array(l1)
print(arr2.dtype)
arr3 = np.array(l2)
print(arr3.dtype)

<U5
float64


##orginal and copied data

In [ ]:
arr = np.array([1,2,3,4,5])#original data
x = arr.copy()              #copy of original data
x[0] = 42

print(arr)
print(x)

[1 2 3 4 5]
[42  2  3  4  5]


In [ ]:
arr = np.array([1,2,3,4,5])#original data
x = arr.view()              #copy of original data
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [ ]:
array1 = np.array([[1,2,3],[2,3,4]])
print(array1)
print(array1.shape)
print(array1.ndim)

[[1 2 3]
 [2 3 4]]
(2, 3)
2


In [ ]:
array2 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

newarr = array2.reshape(4,3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
l1 = [[2,3,4], [5,6,7]]

for i in l1:
  print(i)

[2, 3, 4]
[5, 6, 7]


In [ ]:
array1 = np.array(l1)
print(array1)

[[2 3 4]
 [5 6 7]]


In [ ]:
for i in array1:
  for j in i:
    print(j)

2
3
4
5
6
7


In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr = np.concatenate((arr1,arr2))

print(arr)

[1 2 3 4 5 6]
